build:
  dependencies: []
  maxRunTime: 3600
  system_setup:
    - >
      true
  system_config:
    - >
      true
  git_lfs:
    - >
      export PATH=/home/build-user/bin:$PATH &&
      wget https://github.com/git-lfs/git-lfs/releases/download/v2.3.1/git-lfs-linux-amd64-2.3.1.tar.gz -O - | tar -C /tmp -zxf - &&
      PREFIX=/home/build-user/ /tmp/git-lfs-2.3.1/install.sh
  args:
    tcbuild: ''
    tcpackage: ''
    tests_cmdline: ''
