/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.mozilla.deepspeech.libdeepspeech;

/**
 * A single transcript computed by the model, including a confidence value and
 * the metadata for its constituent tokens.
 */
public class CandidateTranscript {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CandidateTranscript(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CandidateTranscript obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  /**
   * Array of TokenMetadata objects
   */
  public void setTokens(TokenMetadata value) {
    implJNI.CandidateTranscript_tokens_set(swigCPtr, this, TokenMetadata.getCPtr(value), value);
  }

  /**
   * Array of TokenMetadata objects
   */
  public TokenMetadata getTokens() {
    long cPtr = implJNI.CandidateTranscript_tokens_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TokenMetadata(cPtr, false);
  }

  /**
   * Size of the tokens array
   */
  public void setNum_tokens(int value) {
    implJNI.CandidateTranscript_num_tokens_set(swigCPtr, this, value);
  }

  /**
   * Size of the tokens array
   */
  public int getNum_tokens() {
    return implJNI.CandidateTranscript_num_tokens_get(swigCPtr, this);
  }

  /**
   * Approximated confidence value for this transcript. This is roughly the
   * sum of the acoustic model logit values for each timestep/character that
   * contributed to the creation of this transcript.
   */
  public void setConfidence(double value) {
    implJNI.CandidateTranscript_confidence_set(swigCPtr, this, value);
  }

  /**
   * Approximated confidence value for this transcript. This is roughly the
   * sum of the acoustic model logit values for each timestep/character that
   * contributed to the creation of this transcript.
   */
  public double getConfidence() {
    return implJNI.CandidateTranscript_confidence_get(swigCPtr, this);
  }

  /**
   * Retrieve one TokenMetadata element
   *
   * @param i Array index of the TokenMetadata to get
   *
   * @return The TokenMetadata requested or null
   */
  public TokenMetadata getToken(int i) {
    return new TokenMetadata(implJNI.CandidateTranscript_getToken(swigCPtr, this, i), true);
  }

}
